FROM node:lts-alpine
ARG MODE
# Install a simple HTTP server
RUN npm install -g http-server
WORKDIR /app
# Copy package files and install dependencies
COPY package*.json ./
RUN npm install
# Copy the rest of the application code
COPY . .
# Build the app
RUN npm run build -- --mode ${MODE}
EXPOSE 8080
CMD ["http-server", "dist"]